name: Extract EDU(1).zip

on:
  push:
    paths:
      - 'EDU(1).zip'

jobs:
  unzip_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Extract EDU(1).zip
      run: |
        unzip "EDU(1).zip" -d extracted/
        rm "EDU(1).zip"

    - name: Commit extracted files
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add extracted/
        git commit -m "Extracted EDU(1).zip contents"
        git push
